print("##############################")
print("#                            #")
print("#    Rifky Putra Mahardika   #")
print("#        2310817210023       #")
print("#                            #")
print("##############################")